Algoritmo "exemplo1"
var
n1,n2, soma,multiplicacao,divisao,subtracao: real

inicio

escreva("digite um número")
leia(n1)
escreva("digite outro número")
leia(n2)
soma<- n1+n2;
multiplicacao<- n1*n2
divisao<- n1/n2
subtracao<- n1-n2

escreval("resultado de soma", soma)
escreval("resultado de multiplicação", multiplicacao)
escreval("resultado de divisão", divisao)
escreval("resultado de subtrção",subtracao)
fimalgoritmo