Algoritmo "semnome"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 11/04/2023
Var
// Seção de Declarações das variáveis 
j :inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
j <-1
enquanto j <= 10 faca
escreva(j:3)
j <-j +1
fimenquanto

Fimalgoritmo